name: Build & Release

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Fetch Deps (Unix)
      if: runner.os != 'Windows'
      run: |
        chmod +x deps.sh
        ./deps.sh

    - name: Fetch Deps (Windows)
      if: runner.os == 'Windows'
      run: bash ./deps.sh

    - name: Configure CMake
      run: cmake -S . -B build

    - name: Build
      run: cmake --build build --config Release

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: weather-tui-${{ matrix.os }}
        path: |
          build/ascii-weather-tui
          build/Release/ascii-weather-tui.exe
